name: 'Deploy to AWS S3'
description: 'Deploy a static website to an S3 bucket'
inputs:
  bucket:
    description: "The S3 bucket name"
    required: true
  bucket-region:
    description: "The S3 bucket region"
    required: false
    default: 'us-east-1'
  dist-folder:
    description: "The folder to deploy"
    required: true
    default: 'dist'
runs:
  using: 'node16'
  # pre:
  main: 'main.js'
  # post:
