name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies for a Node.js project'
inputs:
  caching:
    description: 'Wheter to cache dependencies or not'
    required: true
    default: 'true' 
outputs:
  used-cache:
    description: 'Whether the cache was used or not'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "::set-output name=cache::${{inputs.caching}}"
      # echo "::set-output name=cache::${{steps.cache.outputs.cache-hit}}"
      # echo 'cache=${{steps.cache.outputs.cache-hit}} >> $GITHUB_OUTPUT'
      shell: bash