name: Events Demo 1
# on: [push, workflow_dispatch]
on:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - main
  #     - 'dev-*' #Any pattern without slashes
  #     - 'feat/**' # Matches any branch whose name starts with 'feat/' and other slashes in

  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
    paths-ignore: # Will ignore all branches that contains  changes in this:
      - '.github/workflows/*'
    # paths: #This means that all branches that contains at least 1 file of this will be trigger this
    #   - 'src/**'
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."